site_name: sqlalchemy-tenants
repo_url: https://github.com/Telemaco019/sqlalchemy-tenants
repo_name: sqlalchemy-tenants

theme:
  name: material

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.path
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
plugins:
  - search
  - mkdocstrings